trigger:
- main

pool:
  name: Default

steps:
- task: UseDotNet@2
  inputs:
    packageType: sdk
    version: 8.x

- script: dotnet restore
  displayName: Restore

- script: dotnet build -c Release
  displayName: Build

- script: dotnet publish WebApplication1/WebApplication1.csproj -c Release -o $(Build.ArtifactStagingDirectory)/publish
  displayName: Publish

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/publish'
    ArtifactName: drop