trigger:
- main

pool:
  name: Default

steps:
- task: UseDotNet@2
  inputs:
    packageType: sdk
    version: 8.x

- script: dotnet restore
  displayName: Restore

- script: dotnet build -c Release
  displayName: Build

- task: DotNetCoreCLI@2
  inputs:
    command: publish
    projects: 'WebApplication1/WebApplication1.csproj'
    arguments: '-c Release -o $(Build.ArtifactStagingDirectory)/publish'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/publish'
    ArtifactName: drop